Upgrade to Django 4 (and other stuff).
That was a lot of yak shaving. I couldn't commit the upgrade to Django 4
because markdown_deux was breaking things somehow:

```
ImportError: cannot import name 'force_unicode' from 'django.utils.encoding'
```

So then I realize markdown_deux has been abandoned and I look for how
you should do Markdown in Django nowadays. I find this…

https://learndjango.com/tutorials/django-markdown-tutorial

…but then it says you should use Bleach with it, so I go looking for
how to use that.

This way feels pretty clean.

https://github.com/pretix/pretix/blob/eeedd9a9c23b62685c2ce63de05d017563b87714/src/pretix/base/templatetags/rich_text.py

via
Markdown Editor for Django - #2 by rixx - Using Django - Django Forum:
https://forum.djangoproject.com/t/markdown-editor-for-django/423/2

I also upgraded some other packages. Compressor will be removed once I
merge the v2 branch, but whatever.