Updating Django.
Ran into an SQLite bug. Updating a roll from /ready caused a weird
error. Updating Django may have been one part of fixing it.

https://stackoverflow.com/a/53637669/96257

Dumping the data and trying to re-create the database by running a
migration and then loading the JSON back in caused an error:

```
django.db.utils.IntegrityError: Problem installing fixture
'/Users/trey/Desktop/film-dump.json': Could not load
contenttypes.ContentType(pk=1): UNIQUE constraint failed:
django_content_type.app_label, django_content_type.model
```

So I dumped and loaded only the `inventory` models and auth.User model.

https://kuttler.eu/en/post/django-db-utils-IntegrityError-duplicate-entry/

Here's hoping the problem doesn't exist on the "production" database.